### ISSUE TITLE
Features request, because there is no option for feature request so i added here

### ISSUE THREAD

**Issue by rairay91** [pejuko/follamac#3]
Adding an option to checbox whether or not follamac let ollama's or other model to search from internet using search engine like duck duck go to grab data and generate up to date answer.

Also, i am not sure if follamac has hardware acceleration. It would be nice if follamac take advantage of CUDA, ROCm, Gaudi and OpenCL, which will let follamac use any gpu to run model.

**Comment by pejuko** [comment]
Follamac is only frontend for ollama and as far as I know ollama models cannot search the internet. Ollama's models are fully local models.

On the other hand, ollama supports GPU acceleration. Follamac does not need to support such things because it only communicates with ollama and does not run models on its own.

**Comment by rairay91** [comment]
> Follamac is only frontend for ollama and as far as I know ollama models cannot search the internet. Ollama's models are fully local models.
> 
> On the other hand, ollama supports GPU acceleration. Follamac does not need to support such things because it only communicates with ollama and does not run models on its own.

🤔But msty on the other hand has an option where if user check it, msty will somehow grab some data from internet(may be first 2-4 webpages) and will give answer, openweb ui is also able to do so. And both of these using ollama.🤔

**Comment by pejuko** [comment]
I'm sorry, I don't plan such feature yet.
